name: Documenting PR on close.

on:
  workflow_dispatch:

  pull_request:
    types: [ closed ]

jobs:
    get_author:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Get Version
          run: cat versions.json

        - name: Read version from JSON
          run: jq ' .version' versions.json

        - name: Get Author Name
          run: |
            cd reports
            echo "PR Author: ${{ github.event.pull_request.user.login }}" >> autoDocs.md
            echo "{Author}=${{ github.event.pull_request.user.login }}" 
            
            echo "Pull Request: [${{ github.event.pull_request.title }}](${{github.event.pull_request.html_url}})" >> autoDocs.md
            
            
